name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: 📝 | Checkout repository
      uses: actions/checkout@v2
    
    - name: 📝 | Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    
    - name: 🏗️ | Build and publish for macOS
      run: |
        cd SkEditor
        for arch in osx-x64 osx-arm64; do
          dotnet restore
          dotnet publish -c Release -r $arch -p:PublishSingleFile=true -p:PublishReadyToRun=true --no-self-contained --nologo -v q --property WarningLevel=0 /clp:ErrorsOnly /p:DebugType=None /p:DebugSymbols=false
        done

    - name: 🛠️ | Create .app structure and zip for both architectures
      run: |
        for arch in osx-x64 osx-arm64; do
          mkdir -p "SkEditor.app/Contents/MacOS"
          mkdir -p "SkEditor.app/Contents/Resources"
          cp -r SkEditor/bin/Release/net8.0/$arch/publish/* "SkEditor.app/Contents/MacOS/"
          cp SkEditor/Info.plist "SkEditor.app/Contents/"
          cp SkEditor/SkEditor.icns "SkEditor.app/Contents/Resources/"
          find SkEditor.app/Contents/MacOS/ -type f -exec chmod +x {} \;
          zip -r "SkEditorMac-$arch.zip" SkEditor.app
          mv "SkEditorMac-$arch.zip" "$arch-SkEditorMac.zip"
        done
    
    - name: 📤 | Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SkEditorMac
        path: "*.zip"
